### ISSUE TITLE
SIG Graphics-Audio Co-Chair Election 2024

### ISSUE THREAD

**Issue by Naomi-Wash** [o3de/sig-graphics-audio#158]
The current co-chair needs to step down; opening an election for a new co-chair.
You can see the election process here: https://github.com/o3de/community/blob/main/O3DE%20Elections/O3DE%20Elections%20Guide.md

```[tasklist]
### Tasks
- [x] Decides the nomination and election timeline. Proposed Nomination: February 20 - Februrary 27, 2024. Election: February 28 -  March 6, 2024.
- [x] On Discord, create an event that links to the GitHub Issue and uses the same issue title, mentioning the nomination and voting dates, and the SIG name: https://github.com/o3de/sig-graphics-audio/issues/158
- [x] Share the event in the SIG Channel, along with the mailing list.
- [x] Monitor the channel during the nomination process, responding to questions, and checking for nominations, acceptances, or declines. Send out reminders as necessary. If there is only one nominee, extend the nomination period by 1-2 weeks. If no one is nominated, the suggested candidate will become the Co-Chair.
- [x] Once at least two nominees are confirmed, prepare the voting survey.
- [x] Announce the results of the Issue and the SIG Channel
```

**Comment by thefranke** [comment]
I nominate Pavel Golovinskii @pgolovin for the co-chair position.

**Comment by Naomi-Wash** [comment]
Nominations are now closed and the voting portion will be launched tomorrow [2/28].

**Comment by galibzon** [comment]
So it seems @antonmic got the most votes?

**Comment by Naomi-Wash** [comment]
No - I still need to open the official vote form.

**Comment by Naomi-Wash** [comment]
The voting form for the co-chair position is now open. 
**The voting will end Thursday, March 6, 2024.**
### **[Please cast your votes!](https://forms.gle/fZwT5AhTKWpH9GQE6)**

**Comment by moudgils** [comment]
naomiwash_lf
Thank you for your votes! I am pleased to announce the results of the SIG-Graphics-Audio election.

There were 6 votes submitted and 5 of those went to Anton Michaels.

**Comment by moudgils** [comment]
@Naomi-Wash Are you able to resolve this ticket and ensure that Anton shows up as co-chair for rendering sig. Thanks.

**Comment by Naomi-Wash** [comment]
Anton Michels @antonmic received 5 out of 6 votes. Anton is now the co-chair of the SIG-Audio-Graphics.
